# Generated by Django 4.2.5 on 2023-11-18 08:43

import apps.accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket",
                to="events.ticket",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="user",
            field=models.ForeignKey(
                default=apps.accounts.models.UserProfile.get_empty_user_profile,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="purchase",
                to="accounts.userprofile",
            ),
        ),
    ]
