# Generated by Django 4.2.5 on 2023-11-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="creating_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
