# Generated by Django 4.2.5 on 2023-11-18 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_creating_time_purchase_creation_time"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="purchase",
            table="Покупки",
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="Профили пользователей",
        ),
    ]
