# Generated by Django 4.2.5 on 2023-11-18 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_purchase_table_alter_userprofile_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
        migrations.AlterModelTable(
            name="purchase",
            table=None,
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="Users",
        ),
    ]
