# Generated by Django 4.2.5 on 2023-11-18 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_userprofile_options_alter_purchase_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchase",
            options={"verbose_name": "покупку", "verbose_name_plural": "Покупки"},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
    ]
