# Generated by Django 4.2.5 on 2023-11-18 08:43

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="")),
                ("end_date", models.DateTimeField(db_index=True, verbose_name="")),
                ("description", models.TextField(verbose_name="")),
                (
                    "ages",
                    models.CharField(
                        choices=[
                            ("0+", "0+"),
                            ("6+", "6+"),
                            ("12+", "12+"),
                            ("14+", "14+"),
                            ("16+", "16+"),
                            ("18+", "18+"),
                        ],
                        default="0+",
                        max_length=3,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="apps/events/static/img", verbose_name=""
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        unique=True,
                        verbose_name="url мероприятия",
                    ),
                ),
                (
                    "genre",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "db_table": "events",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(default=0)),
                ("spot", models.CharField(default="", max_length=50)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "tickets",
            },
        ),
    ]
