# Generated by Django 4.2.5 on 2023-11-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="people_count",
            field=models.IntegerField(default=0),
        ),
    ]
