# Generated by Django 4.2.5 on 2023-11-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_ticket_creating_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="creating_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
