# Generated by Django 4.2.5 on 2023-11-18 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_remove_ticket_creating_time"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="event",
            table="События",
        ),
        migrations.AlterModelTable(
            name="ticket",
            table="Билеты",
        ),
    ]
