# Generated by Django 4.2.5 on 2023-11-18 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("buildings", "0001_initial"),
        ("events", "0007_alter_event_options_alter_ticket_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event",
                to="buildings.building",
            ),
        ),
    ]
