# Generated by Django 4.2.6 on 2023-12-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='filter',
            field=models.CharField(choices=[('all', 'all'), ('sport', 'sport'), ('concerts', 'concerts'), ('festivals', 'festivals'), ('kids', 'kids')], default='all', max_length=50),
        ),
    ]
