# Generated by Django 4.2.5 on 2023-11-26 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("buildings", "0002_building_address_alter_building_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("capacity_balcony", models.IntegerField(default=0)),
                ("capacity_sitting", models.IntegerField(default=0)),
                ("capacity_dance_floor", models.IntegerField(default=0)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area",
                        to="buildings.building",
                    ),
                ),
            ],
            options={
                "db_table": "areas",
            },
        ),
    ]
